version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout

      - run:
          name: Install Newman
          command: npm install -g newman newman-reporter-html

      - run:
          name: Run API Tests with HTML Report
          command: |
            newman run AmpolTest.postman_collection.json \
            -e WeatherAPI.postman_environment.json \
            -r html --reporter-html-export report.html

      - store_artifacts:
          path: report.html

workflows:
  test-workflow:
    jobs:
      - test
